// СПРАВОЧНИК НАИМЕНОВАНИЙ ТОВАРОВ — большой каталог (секции → позиции).
// Источник секций: assets/source-data/Наименования товаров.xlsx (15 секций PF-СС0000).
// Позиции и HS-коды (ТН ВЭД / международный HS, 6 знаков) добавлены как ориентир для
// таможенной классификации ЕС (€3/позиция). ⚠️ HS-коды — представительные, требуют
// финальной проверки таможенным брокером под конкретный товар.
//
// Код позиции: PF-СС____ где СС — номер секции (01..15), последние 4 знака — порядковый
// номер позиции внутри секции (0001, 0002, …). Секция = PF-СС0000.

export type PnItem = {
  /** порядковый номер внутри секции, формирует код PF-СС{seq:0000} */
  seq: number;
  ru: string;
  en: string;
  cn: string;
  /** HS / ТН ВЭД, 6 знаков в формате "XXXX XX" */
  hs: string;
};

export type PnSection = {
  code: string; // PF-СС0000
  ru: string;
  en: string;
  cn: string;
  items: PnItem[];
};

export const PRODUCT_NAME_SECTIONS: PnSection[] = [
  {
    code: "PF-010000",
    ru: "Авто, Мото, Инструмент",
    en: "Auto, Moto, Tool",
    cn: "汽車、摩托車、工具",
    items: [
      { seq: 1, ru: "Автозапчасти (кузовные детали)", en: "Auto body parts", cn: "汽車車身配件", hs: "8708 29" },
      { seq: 2, ru: "Тормозные колодки", en: "Brake pads", cn: "剎車片", hs: "8708 30" },
      { seq: 3, ru: "Автомобильные фильтры", en: "Automotive filters", cn: "汽車濾清器", hs: "8421 23" },
      { seq: 4, ru: "Свечи зажигания", en: "Spark plugs", cn: "火花塞", hs: "8511 10" },
      { seq: 5, ru: "Автомобильные шины", en: "Car tyres", cn: "汽車輪胎", hs: "4011 10" },
      { seq: 6, ru: "Аккумулятор автомобильный", en: "Car battery", cn: "汽車電瓶", hs: "8507 10" },
      { seq: 7, ru: "Моторное масло", en: "Motor oil", cn: "機油", hs: "2710 19" },
      { seq: 8, ru: "Автомагнитола", en: "Car stereo", cn: "汽車音響", hs: "8527 21" },
      { seq: 9, ru: "Видеорегистратор", en: "Dash camera", cn: "行車記錄儀", hs: "8521 90" },
      { seq: 10, ru: "Автомобильные коврики", en: "Car floor mats", cn: "汽車腳墊", hs: "5705 00" },
      { seq: 11, ru: "Чехлы для сидений", en: "Seat covers", cn: "座椅套", hs: "8708 99" },
      { seq: 12, ru: "Мотошлем", en: "Motorcycle helmet", cn: "摩托車頭盔", hs: "6506 10" },
      { seq: 13, ru: "Мотоэкипировка", en: "Motorcycle gear", cn: "摩托車騎行裝備", hs: "6211 33" },
      { seq: 14, ru: "Запчасти для мотоцикла", en: "Motorcycle parts", cn: "摩托車配件", hs: "8714 10" },
      { seq: 15, ru: "Велосипед", en: "Bicycle", cn: "自行車", hs: "8712 00" },
      { seq: 16, ru: "Запчасти для велосипеда", en: "Bicycle parts", cn: "自行車配件", hs: "8714 91" },
      { seq: 17, ru: "Электросамокат", en: "Electric scooter", cn: "電動滑板車", hs: "8711 60" },
      { seq: 18, ru: "Электродрель / шуруповёрт", en: "Electric drill / driver", cn: "電鑽／起子", hs: "8467 21" },
      { seq: 19, ru: "Углошлифмашина (болгарка)", en: "Angle grinder", cn: "角磨機", hs: "8467 29" },
      { seq: 20, ru: "Набор ручного инструмента", en: "Hand tool set", cn: "手動工具套裝", hs: "8206 00" },
      { seq: 21, ru: "Гаечные ключи", en: "Wrenches / spanners", cn: "扳手", hs: "8204 11" },
      { seq: 22, ru: "Отвёртки", en: "Screwdrivers", cn: "螺絲刀", hs: "8205 40" },
      { seq: 23, ru: "Сварочный аппарат", en: "Welding machine", cn: "電焊機", hs: "8515 31" },
      { seq: 24, ru: "Воздушный компрессор", en: "Air compressor", cn: "空氣壓縮機", hs: "8414 80" },
      { seq: 25, ru: "Измерительный инструмент", en: "Measuring tools", cn: "測量工具", hs: "9017 30" },
      { seq: 26, ru: "Крепёж (болты, гайки)", en: "Fasteners (bolts, nuts)", cn: "緊固件（螺栓、螺母）", hs: "7318 15" },
    ],
  },
  {
    code: "PF-020000",
    ru: "Бизнес",
    en: "Business",
    cn: "商業",
    items: [
      { seq: 1, ru: "POS-терминал", en: "POS terminal", cn: "POS 收銀終端", hs: "8470 50" },
      { seq: 2, ru: "Кассовый аппарат", en: "Cash register", cn: "收銀機", hs: "8470 50" },
      { seq: 3, ru: "Сейф", en: "Safe", cn: "保險箱", hs: "8303 00" },
      { seq: 4, ru: "Счётчик банкнот", en: "Banknote counter", cn: "點鈔機", hs: "8472 90" },
      { seq: 5, ru: "Ламинатор", en: "Laminator", cn: "過塑機", hs: "8472 90" },
      { seq: 6, ru: "Брошюровщик", en: "Binding machine", cn: "裝訂機", hs: "8472 90" },
      { seq: 7, ru: "Уничтожитель бумаг (шредер)", en: "Paper shredder", cn: "碎紙機", hs: "8472 90" },
      { seq: 8, ru: "Этикет-пистолет", en: "Label gun", cn: "標價機", hs: "8472 90" },
      { seq: 9, ru: "Детектор валют", en: "Currency detector", cn: "驗鈔機", hs: "8472 90" },
      { seq: 10, ru: "Калькулятор", en: "Calculator", cn: "計算器", hs: "8470 10" },
      { seq: 11, ru: "Торговый стеллаж", en: "Retail shelving", cn: "貨架", hs: "9403 20" },
      { seq: 12, ru: "Витрина торговая", en: "Display showcase", cn: "展示櫃", hs: "9403 20" },
      { seq: 13, ru: "Рекламная стойка", en: "Advertising stand", cn: "廣告展架", hs: "9403 20" },
      { seq: 14, ru: "Складская тележка", en: "Warehouse trolley", cn: "倉儲手推車", hs: "8716 80" },
      { seq: 15, ru: "Рабочая униформа", en: "Work uniform", cn: "工作制服", hs: "6211 33" },
      { seq: 16, ru: "Держатель бейджа", en: "Badge holder", cn: "工牌卡套", hs: "3926 90" },
      { seq: 17, ru: "Печати и штампы", en: "Stamps and seals", cn: "印章", hs: "9611 00" },
      { seq: 18, ru: "Ценникодержатель", en: "Price tag holder", cn: "標價牌夾", hs: "3926 90" },
      { seq: 19, ru: "Терминал самообслуживания", en: "Self-service kiosk", cn: "自助終端機", hs: "8470 50" },
      { seq: 20, ru: "Сканер штрих-кодов", en: "Barcode scanner", cn: "條碼掃描器", hs: "8471 90" },
    ],
  },
  {
    code: "PF-030000",
    ru: "Бытовая техника",
    en: "Appliances",
    cn: "家電",
    items: [
      { seq: 1, ru: "Холодильник", en: "Refrigerator", cn: "冰箱", hs: "8418 10" },
      { seq: 2, ru: "Морозильник", en: "Freezer", cn: "冷凍櫃", hs: "8418 30" },
      { seq: 3, ru: "Стиральная машина", en: "Washing machine", cn: "洗衣機", hs: "8450 11" },
      { seq: 4, ru: "Посудомоечная машина", en: "Dishwasher", cn: "洗碗機", hs: "8422 11" },
      { seq: 5, ru: "Варочная панель / электроплита", en: "Cooktop / electric stove", cn: "電磁爐／電爐", hs: "8516 60" },
      { seq: 6, ru: "Микроволновая печь", en: "Microwave oven", cn: "微波爐", hs: "8516 50" },
      { seq: 7, ru: "Кухонная вытяжка", en: "Range hood", cn: "抽油煙機", hs: "8414 60" },
      { seq: 8, ru: "Пылесос", en: "Vacuum cleaner", cn: "吸塵器", hs: "8508 11" },
      { seq: 9, ru: "Робот-пылесос", en: "Robot vacuum", cn: "掃地機器人", hs: "8508 11" },
      { seq: 10, ru: "Утюг", en: "Iron", cn: "熨斗", hs: "8516 40" },
      { seq: 11, ru: "Кондиционер", en: "Air conditioner", cn: "空調", hs: "8415 10" },
      { seq: 12, ru: "Вентилятор", en: "Fan", cn: "電風扇", hs: "8414 51" },
      { seq: 13, ru: "Обогреватель", en: "Space heater", cn: "取暖器", hs: "8516 29" },
      { seq: 14, ru: "Водонагреватель", en: "Water heater", cn: "熱水器", hs: "8516 10" },
      { seq: 15, ru: "Электрочайник", en: "Electric kettle", cn: "電熱水壺", hs: "8516 79" },
      { seq: 16, ru: "Кофемашина", en: "Coffee machine", cn: "咖啡機", hs: "8516 71" },
      { seq: 17, ru: "Блендер / миксер", en: "Blender / mixer", cn: "攪拌機", hs: "8509 40" },
      { seq: 18, ru: "Мясорубка", en: "Meat grinder", cn: "絞肉機", hs: "8509 40" },
      { seq: 19, ru: "Тостер", en: "Toaster", cn: "烤麵包機", hs: "8516 72" },
      { seq: 20, ru: "Мультиварка", en: "Multicooker", cn: "多功能電飯煲", hs: "8516 60" },
      { seq: 21, ru: "Фен для волос", en: "Hair dryer", cn: "吹風機", hs: "8516 31" },
      { seq: 22, ru: "Швейная машина", en: "Sewing machine", cn: "縫紉機", hs: "8452 10" },
      { seq: 23, ru: "Увлажнитель воздуха", en: "Air humidifier", cn: "加濕器", hs: "8509 80" },
      { seq: 24, ru: "Очиститель воздуха", en: "Air purifier", cn: "空氣淨化器", hs: "8421 39" },
    ],
  },
  {
    code: "PF-040000",
    ru: "Зоотовары",
    en: "Pet supplies",
    cn: "寵物用品",
    items: [
      { seq: 1, ru: "Корм для собак", en: "Dog food", cn: "狗糧", hs: "2309 10" },
      { seq: 2, ru: "Корм для кошек", en: "Cat food", cn: "貓糧", hs: "2309 10" },
      { seq: 3, ru: "Лакомства для животных", en: "Pet treats", cn: "寵物零食", hs: "2309 10" },
      { seq: 4, ru: "Наполнитель для туалета", en: "Cat litter", cn: "貓砂", hs: "3824 99" },
      { seq: 5, ru: "Лоток для кошек", en: "Cat litter tray", cn: "貓砂盆", hs: "3924 90" },
      { seq: 6, ru: "Переноска для животных", en: "Pet carrier", cn: "寵物提籠", hs: "4202 92" },
      { seq: 7, ru: "Клетка для животных", en: "Pet cage", cn: "寵物籠", hs: "7326 90" },
      { seq: 8, ru: "Аквариум", en: "Aquarium", cn: "魚缸", hs: "7020 00" },
      { seq: 9, ru: "Фильтр для аквариума", en: "Aquarium filter", cn: "魚缸過濾器", hs: "8421 21" },
      { seq: 10, ru: "Ошейник / поводок", en: "Collar / leash", cn: "項圈／牽引繩", hs: "4201 00" },
      { seq: 11, ru: "Шлейка", en: "Harness", cn: "胸背帶", hs: "4201 00" },
      { seq: 12, ru: "Игрушки для животных", en: "Pet toys", cn: "寵物玩具", hs: "4201 00" },
      { seq: 13, ru: "Когтеточка", en: "Scratching post", cn: "貓抓板", hs: "4421 99" },
      { seq: 14, ru: "Миска для животных", en: "Pet bowl", cn: "寵物碗", hs: "3924 10" },
      { seq: 15, ru: "Автопоилка", en: "Automatic water dispenser", cn: "自動飲水器", hs: "3924 90" },
      { seq: 16, ru: "Домик / лежанка для животных", en: "Pet house / bed", cn: "寵物窩", hs: "4421 99" },
      { seq: 17, ru: "Одежда для животных", en: "Pet clothing", cn: "寵物服裝", hs: "4201 00" },
      { seq: 18, ru: "Шампунь для животных", en: "Pet shampoo", cn: "寵物洗毛液", hs: "3307 90" },
      { seq: 19, ru: "Витамины для животных", en: "Pet vitamins", cn: "寵物營養品", hs: "2309 90" },
      { seq: 20, ru: "Клетка для птиц", en: "Bird cage", cn: "鳥籠", hs: "7326 90" },
    ],
  },
  {
    code: "PF-050000",
    ru: "Красота и здоровье",
    en: "Health and beauty",
    cn: "健康和美麗",
    items: [
      { seq: 1, ru: "Помада", en: "Lipstick", cn: "口紅", hs: "3304 10" },
      { seq: 2, ru: "Тушь для ресниц", en: "Mascara", cn: "睫毛膏", hs: "3304 20" },
      { seq: 3, ru: "Тени для век", en: "Eyeshadow", cn: "眼影", hs: "3304 20" },
      { seq: 4, ru: "Тональный крем", en: "Foundation", cn: "粉底液", hs: "3304 99" },
      { seq: 5, ru: "Пудра", en: "Face powder", cn: "蜜粉", hs: "3304 91" },
      { seq: 6, ru: "Крем для лица", en: "Face cream", cn: "面霜", hs: "3304 99" },
      { seq: 7, ru: "Сыворотка для лица", en: "Face serum", cn: "面部精華", hs: "3304 99" },
      { seq: 8, ru: "Маска для лица", en: "Face mask", cn: "面膜", hs: "3304 99" },
      { seq: 9, ru: "Шампунь", en: "Shampoo", cn: "洗髮水", hs: "3305 10" },
      { seq: 10, ru: "Бальзам / краска для волос", en: "Hair conditioner / dye", cn: "護髮素／染髮劑", hs: "3305 90" },
      { seq: 11, ru: "Гель для душа", en: "Shower gel", cn: "沐浴露", hs: "3401 30" },
      { seq: 12, ru: "Мыло", en: "Soap", cn: "香皂", hs: "3401 11" },
      { seq: 13, ru: "Духи / парфюм", en: "Perfume", cn: "香水", hs: "3303 00" },
      { seq: 14, ru: "Дезодорант", en: "Deodorant", cn: "止汗劑", hs: "3307 20" },
      { seq: 15, ru: "Зубная паста", en: "Toothpaste", cn: "牙膏", hs: "3306 10" },
      { seq: 16, ru: "Лак / средства для ногтей", en: "Nail polish / care", cn: "指甲油", hs: "3304 30" },
      { seq: 17, ru: "Массажёр", en: "Massager", cn: "按摩儀", hs: "9019 10" },
      { seq: 18, ru: "Тонометр", en: "Blood pressure monitor", cn: "血壓計", hs: "9018 90" },
      { seq: 19, ru: "Термометр медицинский", en: "Medical thermometer", cn: "體溫計", hs: "9025 19" },
      { seq: 20, ru: "Пульсоксиметр", en: "Pulse oximeter", cn: "血氧儀", hs: "9018 19" },
      { seq: 21, ru: "Небулайзер / ингалятор", en: "Nebulizer / inhaler", cn: "霧化器", hs: "9019 20" },
      { seq: 22, ru: "Электрическая зубная щётка", en: "Electric toothbrush", cn: "電動牙刷", hs: "8509 80" },
      { seq: 23, ru: "Эпилятор", en: "Epilator", cn: "脫毛器", hs: "8510 30" },
      { seq: 24, ru: "Машинка для стрижки волос", en: "Hair clipper", cn: "理髮器", hs: "8510 20" },
      { seq: 25, ru: "Пластырь / бинты", en: "Plaster / bandage", cn: "膏藥／繃帶", hs: "3005 10" },
      { seq: 26, ru: "Витамины и БАДы", en: "Vitamins and supplements", cn: "維生素及保健品", hs: "2106 90" },
      { seq: 27, ru: "Медицинские маски", en: "Medical masks", cn: "醫用口罩", hs: "6307 90" },
    ],
  },
  {
    code: "PF-060000",
    ru: "Ноутбуки, ПК, оргтехника",
    en: "Laptops, PCs, office equipment",
    cn: "筆記本電腦、個人電腦、辦公設備",
    items: [
      { seq: 1, ru: "Ноутбук", en: "Laptop", cn: "筆記本電腦", hs: "8471 30" },
      { seq: 2, ru: "Настольный ПК / моноблок", en: "Desktop PC / all-in-one", cn: "台式電腦／一體機", hs: "8471 41" },
      { seq: 3, ru: "Материнская плата", en: "Motherboard", cn: "主板", hs: "8473 30" },
      { seq: 4, ru: "Процессор (CPU)", en: "Processor (CPU)", cn: "處理器", hs: "8542 31" },
      { seq: 5, ru: "Видеокарта", en: "Graphics card", cn: "顯卡", hs: "8473 30" },
      { seq: 6, ru: "Оперативная память (RAM)", en: "RAM memory", cn: "內存條", hs: "8473 30" },
      { seq: 7, ru: "SSD-накопитель", en: "SSD drive", cn: "固態硬盤", hs: "8471 70" },
      { seq: 8, ru: "Жёсткий диск (HDD)", en: "Hard drive (HDD)", cn: "機械硬盤", hs: "8471 70" },
      { seq: 9, ru: "Блок питания ПК", en: "PC power supply", cn: "電腦電源", hs: "8504 40" },
      { seq: 10, ru: "Корпус ПК", en: "PC case", cn: "電腦機箱", hs: "8473 30" },
      { seq: 11, ru: "Система охлаждения / кулер", en: "Cooling system", cn: "散熱器", hs: "8473 30" },
      { seq: 12, ru: "Монитор", en: "Monitor", cn: "顯示器", hs: "8528 52" },
      { seq: 13, ru: "Клавиатура", en: "Keyboard", cn: "鍵盤", hs: "8471 60" },
      { seq: 14, ru: "Мышь компьютерная", en: "Computer mouse", cn: "鼠標", hs: "8471 60" },
      { seq: 15, ru: "Веб-камера", en: "Webcam", cn: "網絡攝像頭", hs: "8525 89" },
      { seq: 16, ru: "Принтер", en: "Printer", cn: "打印機", hs: "8443 32" },
      { seq: 17, ru: "МФУ (принтер-сканер)", en: "All-in-one printer", cn: "多功能一體機", hs: "8443 31" },
      { seq: 18, ru: "Сканер", en: "Scanner", cn: "掃描儀", hs: "8471 60" },
      { seq: 19, ru: "Картридж для принтера", en: "Printer cartridge", cn: "打印機墨盒", hs: "8443 99" },
      { seq: 20, ru: "Проектор", en: "Projector", cn: "投影儀", hs: "8528 62" },
      { seq: 21, ru: "ИБП (UPS)", en: "UPS", cn: "不間斷電源", hs: "8504 40" },
      { seq: 22, ru: "Внешний жёсткий диск", en: "External hard drive", cn: "移動硬盤", hs: "8471 70" },
      { seq: 23, ru: "USB-флешка / карта памяти", en: "USB flash / memory card", cn: "U盤／存儲卡", hs: "8523 51" },
      { seq: 24, ru: "Док-станция", en: "Docking station", cn: "擴展塢", hs: "8471 80" },
      { seq: 25, ru: "Сетевой фильтр", en: "Surge protector", cn: "電源排插", hs: "8536 30" },
    ],
  },
  {
    code: "PF-070000",
    ru: "Одежда",
    en: "Clothing",
    cn: "衣服",
    items: [
      { seq: 1, ru: "Футболка", en: "T-shirt", cn: "T恤", hs: "6109 10" },
      { seq: 2, ru: "Рубашка", en: "Shirt", cn: "襯衫", hs: "6205 20" },
      { seq: 3, ru: "Блузка", en: "Blouse", cn: "女式襯衫", hs: "6206 30" },
      { seq: 4, ru: "Джинсы", en: "Jeans", cn: "牛仔褲", hs: "6203 42" },
      { seq: 5, ru: "Брюки", en: "Trousers", cn: "長褲", hs: "6203 42" },
      { seq: 6, ru: "Шорты", en: "Shorts", cn: "短褲", hs: "6203 43" },
      { seq: 7, ru: "Юбка", en: "Skirt", cn: "裙子", hs: "6204 52" },
      { seq: 8, ru: "Платье", en: "Dress", cn: "連衣裙", hs: "6204 42" },
      { seq: 9, ru: "Куртка", en: "Jacket", cn: "夾克", hs: "6201 40" },
      { seq: 10, ru: "Пальто", en: "Coat", cn: "大衣", hs: "6201 40" },
      { seq: 11, ru: "Пуховик", en: "Down jacket", cn: "羽絨服", hs: "6201 40" },
      { seq: 12, ru: "Пиджак", en: "Blazer", cn: "西裝外套", hs: "6203 33" },
      { seq: 13, ru: "Свитер / джемпер", en: "Sweater / jumper", cn: "毛衣", hs: "6110 20" },
      { seq: 14, ru: "Худи / толстовка", en: "Hoodie / sweatshirt", cn: "衛衣", hs: "6110 30" },
      { seq: 15, ru: "Спортивный костюм", en: "Tracksuit", cn: "運動套裝", hs: "6112 12" },
      { seq: 16, ru: "Нижнее бельё", en: "Underwear", cn: "內衣", hs: "6108 21" },
      { seq: 17, ru: "Носки", en: "Socks", cn: "襪子", hs: "6115 95" },
      { seq: 18, ru: "Колготки", en: "Tights", cn: "連褲襪", hs: "6115 21" },
      { seq: 19, ru: "Купальник", en: "Swimwear", cn: "泳衣", hs: "6112 41" },
      { seq: 20, ru: "Пижама", en: "Pyjamas", cn: "睡衣", hs: "6108 31" },
      { seq: 21, ru: "Халат", en: "Bathrobe", cn: "浴袍", hs: "6108 91" },
      { seq: 22, ru: "Ветровка", en: "Windbreaker", cn: "風衣", hs: "6201 40" },
      { seq: 23, ru: "Джинсовая куртка", en: "Denim jacket", cn: "牛仔外套", hs: "6201 30" },
      { seq: 24, ru: "Термобельё", en: "Thermal underwear", cn: "保暖內衣", hs: "6109 90" },
      { seq: 25, ru: "Перчатки (текстиль)", en: "Gloves (textile)", cn: "手套（針織）", hs: "6116 93" },
      { seq: 26, ru: "Шапка", en: "Hat / beanie", cn: "帽子", hs: "6505 00" },
      { seq: 27, ru: "Шарф", en: "Scarf", cn: "圍巾", hs: "6117 10" },
    ],
  },
  {
    code: "PF-080000",
    ru: "Продукты питания, напитки, БАДы",
    en: "Food, drinks, dietary supplements",
    cn: "食品、飲料、膳食補充劑",
    items: [
      { seq: 1, ru: "Чай", en: "Tea", cn: "茶葉", hs: "0902 30" },
      { seq: 2, ru: "Кофе", en: "Coffee", cn: "咖啡", hs: "0901 21" },
      { seq: 3, ru: "Снеки / чипсы", en: "Snacks / chips", cn: "零食／薯片", hs: "1905 90" },
      { seq: 4, ru: "Печенье", en: "Biscuits", cn: "餅乾", hs: "1905 31" },
      { seq: 5, ru: "Шоколад", en: "Chocolate", cn: "巧克力", hs: "1806 90" },
      { seq: 6, ru: "Конфеты", en: "Candy", cn: "糖果", hs: "1704 90" },
      { seq: 7, ru: "Сухофрукты", en: "Dried fruit", cn: "果乾", hs: "0813 50" },
      { seq: 8, ru: "Орехи", en: "Nuts", cn: "堅果", hs: "2008 19" },
      { seq: 9, ru: "Мёд", en: "Honey", cn: "蜂蜜", hs: "0409 00" },
      { seq: 10, ru: "Специи и приправы", en: "Spices and seasonings", cn: "調味料", hs: "2103 90" },
      { seq: 11, ru: "Соусы", en: "Sauces", cn: "醬料", hs: "2103 90" },
      { seq: 12, ru: "Лапша быстрого приготовления", en: "Instant noodles", cn: "方便麵", hs: "1902 30" },
      { seq: 13, ru: "Крупы", en: "Grains / cereals", cn: "穀物", hs: "1104 19" },
      { seq: 14, ru: "Растительное масло", en: "Vegetable oil", cn: "食用油", hs: "1512 19" },
      { seq: 15, ru: "Соки", en: "Juices", cn: "果汁", hs: "2009 89" },
      { seq: 16, ru: "Газированные напитки", en: "Soft drinks", cn: "碳酸飲料", hs: "2202 10" },
      { seq: 17, ru: "Энергетические напитки", en: "Energy drinks", cn: "能量飲料", hs: "2202 99" },
      { seq: 18, ru: "Вода минеральная", en: "Mineral water", cn: "礦泉水", hs: "2201 10" },
      { seq: 19, ru: "Сухое молоко", en: "Milk powder", cn: "奶粉", hs: "0402 21" },
      { seq: 20, ru: "Детское питание", en: "Baby food", cn: "嬰兒食品", hs: "1901 10" },
      { seq: 21, ru: "Мясные снеки (джерки)", en: "Meat snacks (jerky)", cn: "肉乾", hs: "1602 50" },
      { seq: 22, ru: "Сушёные морепродукты", en: "Dried seafood", cn: "海味乾貨", hs: "0305 59" },
      { seq: 23, ru: "Протеин (спортпит)", en: "Protein supplement", cn: "蛋白粉", hs: "2106 90" },
      { seq: 24, ru: "БАДы / добавки", en: "Dietary supplements", cn: "膳食補充劑", hs: "2106 90" },
    ],
  },
  {
    code: "PF-090000",
    ru: "Сетевое оборудование",
    en: "Network hardware",
    cn: "網絡硬件",
    items: [
      { seq: 1, ru: "Wi-Fi роутер", en: "Wi-Fi router", cn: "無線路由器", hs: "8517 62" },
      { seq: 2, ru: "Коммутатор (switch)", en: "Network switch", cn: "交換機", hs: "8517 62" },
      { seq: 3, ru: "Точка доступа Wi-Fi", en: "Wi-Fi access point", cn: "無線接入點", hs: "8517 62" },
      { seq: 4, ru: "Сетевая карта", en: "Network card", cn: "網卡", hs: "8517 62" },
      { seq: 5, ru: "Модем", en: "Modem", cn: "調製解調器", hs: "8517 62" },
      { seq: 6, ru: "Wi-Fi адаптер", en: "Wi-Fi adapter", cn: "無線網卡", hs: "8517 62" },
      { seq: 7, ru: "Усилитель сигнала (репитер)", en: "Signal repeater", cn: "信號放大器", hs: "8517 62" },
      { seq: 8, ru: "Сетевой кабель (патч-корд)", en: "Patch cord", cn: "網線", hs: "8544 42" },
      { seq: 9, ru: "Оптоволоконный кабель", en: "Fiber optic cable", cn: "光纖線", hs: "8544 70" },
      { seq: 10, ru: "Коннекторы RJ-45", en: "RJ-45 connectors", cn: "水晶頭", hs: "8536 69" },
      { seq: 11, ru: "Патч-панель", en: "Patch panel", cn: "配線架", hs: "8517 62" },
      { seq: 12, ru: "Сетевое хранилище (NAS)", en: "NAS storage", cn: "網絡存儲", hs: "8471 70" },
      { seq: 13, ru: "Медиаконвертер", en: "Media converter", cn: "光電轉換器", hs: "8517 62" },
      { seq: 14, ru: "PoE-инжектор", en: "PoE injector", cn: "PoE 供電器", hs: "8517 62" },
      { seq: 15, ru: "Антенна Wi-Fi", en: "Wi-Fi antenna", cn: "無線天線", hs: "8517 71" },
      { seq: 16, ru: "4G/5G модем", en: "4G/5G modem", cn: "4G/5G 上網卡", hs: "8517 62" },
      { seq: 17, ru: "IP-камера", en: "IP camera", cn: "網絡攝像機", hs: "8525 89" },
      { seq: 18, ru: "Серверное оборудование", en: "Server hardware", cn: "服務器", hs: "8471 50" },
      { seq: 19, ru: "Серверный шкаф (стойка)", en: "Server rack", cn: "服務器機櫃", hs: "9403 20" },
      { seq: 20, ru: "KVM-переключатель", en: "KVM switch", cn: "KVM 切換器", hs: "8471 80" },
    ],
  },
  {
    code: "PF-100000",
    ru: "Спорт, увлечения, хобби",
    en: "Sports, hobbies",
    cn: "運動、愛好",
    items: [
      { seq: 1, ru: "Гантели", en: "Dumbbells", cn: "啞鈴", hs: "9506 91" },
      { seq: 2, ru: "Штанга и диски", en: "Barbell and plates", cn: "槓鈴", hs: "9506 91" },
      { seq: 3, ru: "Гиря", en: "Kettlebell", cn: "壺鈴", hs: "9506 91" },
      { seq: 4, ru: "Тренажёр", en: "Exercise machine", cn: "健身器材", hs: "9506 91" },
      { seq: 5, ru: "Беговая дорожка", en: "Treadmill", cn: "跑步機", hs: "9506 91" },
      { seq: 6, ru: "Велотренажёр", en: "Exercise bike", cn: "健身單車", hs: "9506 91" },
      { seq: 7, ru: "Коврик для йоги", en: "Yoga mat", cn: "瑜伽墊", hs: "9506 91" },
      { seq: 8, ru: "Эспандер", en: "Resistance band", cn: "拉力帶", hs: "9506 91" },
      { seq: 9, ru: "Мяч футбольный / баскетбольный", en: "Football / basketball", cn: "足球／籃球", hs: "9506 62" },
      { seq: 10, ru: "Скакалка", en: "Jump rope", cn: "跳繩", hs: "9506 91" },
      { seq: 11, ru: "Ракетка теннисная", en: "Tennis racket", cn: "網球拍", hs: "9506 51" },
      { seq: 12, ru: "Ракетка для бадминтона", en: "Badminton racket", cn: "羽毛球拍", hs: "9506 59" },
      { seq: 13, ru: "Набор настольного тенниса", en: "Table tennis set", cn: "乒乓球套裝", hs: "9506 40" },
      { seq: 14, ru: "Палатка", en: "Tent", cn: "帳篷", hs: "6306 22" },
      { seq: 15, ru: "Спальный мешок", en: "Sleeping bag", cn: "睡袋", hs: "9404 30" },
      { seq: 16, ru: "Туристический рюкзак", en: "Hiking backpack", cn: "登山背包", hs: "4202 92" },
      { seq: 17, ru: "Удочка / спиннинг", en: "Fishing rod", cn: "魚竿", hs: "9507 10" },
      { seq: 18, ru: "Рыболовная катушка", en: "Fishing reel", cn: "漁輪", hs: "9507 30" },
      { seq: 19, ru: "Ролики", en: "Roller skates", cn: "輪滑鞋", hs: "9506 70" },
      { seq: 20, ru: "Скейтборд", en: "Skateboard", cn: "滑板", hs: "9506 99" },
      { seq: 21, ru: "Плавательные очки", en: "Swimming goggles", cn: "泳鏡", hs: "9004 90" },
      { seq: 22, ru: "Настольные игры", en: "Board games", cn: "桌遊", hs: "9504 90" },
      { seq: 23, ru: "Пазлы", en: "Puzzles", cn: "拼圖", hs: "9503 00" },
      { seq: 24, ru: "Шахматы / дартс", en: "Chess / darts", cn: "象棋／飛鏢", hs: "9504 90" },
    ],
  },
  {
    code: "PF-110000",
    ru: "Сумки, обувь, аксессуары",
    en: "Bags, shoes, accessories",
    cn: "包包、鞋子、配飾",
    items: [
      { seq: 1, ru: "Сумка женская", en: "Women's handbag", cn: "女士手袋", hs: "4202 21" },
      { seq: 2, ru: "Сумка мужская", en: "Men's bag", cn: "男士包", hs: "4202 91" },
      { seq: 3, ru: "Рюкзак", en: "Backpack", cn: "背包", hs: "4202 92" },
      { seq: 4, ru: "Чемодан", en: "Suitcase", cn: "行李箱", hs: "4202 12" },
      { seq: 5, ru: "Дорожная сумка", en: "Travel bag", cn: "旅行袋", hs: "4202 92" },
      { seq: 6, ru: "Кошелёк / портмоне", en: "Wallet", cn: "錢包", hs: "4202 31" },
      { seq: 7, ru: "Клатч", en: "Clutch", cn: "手拿包", hs: "4202 21" },
      { seq: 8, ru: "Косметичка", en: "Cosmetic bag", cn: "化妝包", hs: "4202 32" },
      { seq: 9, ru: "Сумка через плечо", en: "Shoulder bag", cn: "單肩包", hs: "4202 22" },
      { seq: 10, ru: "Кроссовки", en: "Sneakers", cn: "運動鞋", hs: "6404 11" },
      { seq: 11, ru: "Кеды", en: "Canvas shoes", cn: "帆布鞋", hs: "6404 19" },
      { seq: 12, ru: "Туфли", en: "Dress shoes", cn: "皮鞋", hs: "6403 59" },
      { seq: 13, ru: "Ботинки / сапоги", en: "Boots", cn: "靴子", hs: "6403 91" },
      { seq: 14, ru: "Сандалии", en: "Sandals", cn: "涼鞋", hs: "6402 99" },
      { seq: 15, ru: "Тапочки", en: "Slippers", cn: "拖鞋", hs: "6405 20" },
      { seq: 16, ru: "Сланцы / шлёпанцы", en: "Flip-flops", cn: "人字拖", hs: "6402 20" },
      { seq: 17, ru: "Резиновые сапоги", en: "Rubber boots", cn: "雨靴", hs: "6401 92" },
      { seq: 18, ru: "Ремень кожаный", en: "Leather belt", cn: "皮帶", hs: "4203 30" },
      { seq: 19, ru: "Часы наручные", en: "Wristwatch", cn: "手錶", hs: "9102 11" },
      { seq: 20, ru: "Солнцезащитные очки", en: "Sunglasses", cn: "太陽鏡", hs: "9004 10" },
      { seq: 21, ru: "Очки (оправа)", en: "Eyeglass frames", cn: "眼鏡框", hs: "9003 11" },
      { seq: 22, ru: "Бижутерия", en: "Costume jewellery", cn: "仿飾品", hs: "7117 19" },
      { seq: 23, ru: "Ювелирные изделия", en: "Jewellery", cn: "首飾", hs: "7113 19" },
      { seq: 24, ru: "Кепка / головной убор", en: "Cap / headwear", cn: "帽子", hs: "6505 00" },
      { seq: 25, ru: "Перчатки кожаные", en: "Leather gloves", cn: "皮手套", hs: "4203 29" },
      { seq: 26, ru: "Зонт", en: "Umbrella", cn: "雨傘", hs: "6601 91" },
    ],
  },
  {
    code: "PF-120000",
    ru: "Товары для детей",
    en: "Goods for kids",
    cn: "兒童用品",
    items: [
      { seq: 1, ru: "Подгузники", en: "Diapers", cn: "紙尿褲", hs: "9619 00" },
      { seq: 2, ru: "Детские влажные салфетки", en: "Baby wipes", cn: "嬰兒濕巾", hs: "3401 19" },
      { seq: 3, ru: "Детская бутылочка", en: "Baby bottle", cn: "奶瓶", hs: "3924 90" },
      { seq: 4, ru: "Соска-пустышка", en: "Pacifier", cn: "安撫奶嘴", hs: "4014 90" },
      { seq: 5, ru: "Молокоотсос", en: "Breast pump", cn: "吸奶器", hs: "9018 90" },
      { seq: 6, ru: "Детская смесь", en: "Infant formula", cn: "嬰兒配方奶粉", hs: "1901 10" },
      { seq: 7, ru: "Коляска детская", en: "Baby stroller", cn: "嬰兒車", hs: "8715 00" },
      { seq: 8, ru: "Автокресло детское", en: "Child car seat", cn: "兒童安全座椅", hs: "9401 80" },
      { seq: 9, ru: "Кроватка детская", en: "Baby crib", cn: "嬰兒床", hs: "9403 60" },
      { seq: 10, ru: "Манеж", en: "Playpen", cn: "嬰兒圍欄", hs: "9403 89" },
      { seq: 11, ru: "Стульчик для кормления", en: "High chair", cn: "餐椅", hs: "9401 80" },
      { seq: 12, ru: "Ходунки / прыгунки", en: "Baby walker", cn: "學步車", hs: "9503 00" },
      { seq: 13, ru: "Развивающие игрушки", en: "Educational toys", cn: "益智玩具", hs: "9503 00" },
      { seq: 14, ru: "Конструктор", en: "Building blocks", cn: "積木", hs: "9503 00" },
      { seq: 15, ru: "Кукла", en: "Doll", cn: "娃娃", hs: "9503 00" },
      { seq: 16, ru: "Мягкая игрушка", en: "Plush toy", cn: "毛絨玩具", hs: "9503 00" },
      { seq: 17, ru: "Игрушечные машинки", en: "Toy cars", cn: "玩具車", hs: "9503 00" },
      { seq: 18, ru: "Детская одежда", en: "Children's clothing", cn: "童裝", hs: "6111 20" },
      { seq: 19, ru: "Детская обувь", en: "Children's shoes", cn: "童鞋", hs: "6402 91" },
      { seq: 20, ru: "Пелёнки", en: "Swaddle blankets", cn: "包被", hs: "6302 60" },
      { seq: 21, ru: "Радионяня", en: "Baby monitor", cn: "嬰兒監護器", hs: "8525 89" },
      { seq: 22, ru: "Детский горшок", en: "Potty", cn: "兒童便盆", hs: "3922 90" },
      { seq: 23, ru: "Термометр детский", en: "Baby thermometer", cn: "兒童體溫計", hs: "9025 19" },
    ],
  },
  {
    code: "PF-130000",
    ru: "Товары для дома",
    en: "Household products",
    cn: "家庭用品",
    items: [
      { seq: 1, ru: "Постельное бельё", en: "Bed linen", cn: "床上用品", hs: "6302 31" },
      { seq: 2, ru: "Одеяло", en: "Blanket / duvet", cn: "被子", hs: "9404 40" },
      { seq: 3, ru: "Подушка", en: "Pillow", cn: "枕頭", hs: "9404 90" },
      { seq: 4, ru: "Плед", en: "Throw blanket", cn: "毛毯", hs: "6301 40" },
      { seq: 5, ru: "Полотенце", en: "Towel", cn: "毛巾", hs: "6302 60" },
      { seq: 6, ru: "Шторы", en: "Curtains", cn: "窗簾", hs: "6303 92" },
      { seq: 7, ru: "Ковёр", en: "Carpet / rug", cn: "地毯", hs: "5705 00" },
      { seq: 8, ru: "Посуда (тарелки)", en: "Tableware (plates)", cn: "餐具（碟盤）", hs: "6912 00" },
      { seq: 9, ru: "Кастрюля / сковорода", en: "Pot / frying pan", cn: "鍋具", hs: "7323 93" },
      { seq: 10, ru: "Набор ножей", en: "Knife set", cn: "刀具套裝", hs: "8211 10" },
      { seq: 11, ru: "Столовые приборы", en: "Cutlery", cn: "餐具（刀叉）", hs: "8215 20" },
      { seq: 12, ru: "Стаканы / бокалы", en: "Glasses / tumblers", cn: "玻璃杯", hs: "7013 37" },
      { seq: 13, ru: "Контейнеры для еды", en: "Food containers", cn: "保鮮盒", hs: "3924 10" },
      { seq: 14, ru: "Термос", en: "Thermos", cn: "保溫杯", hs: "9617 00" },
      { seq: 15, ru: "Органайзер для хранения", en: "Storage organizer", cn: "收納盒", hs: "3924 90" },
      { seq: 16, ru: "Вешалки", en: "Clothes hangers", cn: "衣架", hs: "3923 90" },
      { seq: 17, ru: "Сушилка для белья", en: "Clothes drying rack", cn: "晾衣架", hs: "7323 99" },
      { seq: 18, ru: "Мусорное ведро", en: "Trash bin", cn: "垃圾桶", hs: "3924 90" },
      { seq: 19, ru: "Швабра / щётка", en: "Mop / brush", cn: "拖把／掃帚", hs: "9603 90" },
      { seq: 20, ru: "Стиральный порошок", en: "Laundry detergent", cn: "洗衣粉", hs: "3402 50" },
      { seq: 21, ru: "Средства для уборки", en: "Cleaning products", cn: "清潔劑", hs: "3402 90" },
      { seq: 22, ru: "Освежитель воздуха", en: "Air freshener", cn: "空氣清新劑", hs: "3307 49" },
      { seq: 23, ru: "Свечи", en: "Candles", cn: "蠟燭", hs: "3406 00" },
      { seq: 24, ru: "Настенные часы", en: "Wall clock", cn: "掛鐘", hs: "9105 21" },
      { seq: 25, ru: "Зеркало", en: "Mirror", cn: "鏡子", hs: "7009 92" },
      { seq: 26, ru: "Ваза", en: "Vase", cn: "花瓶", hs: "6913 90" },
      { seq: 27, ru: "Рамка для фото", en: "Photo frame", cn: "相框", hs: "4414 90" },
      { seq: 28, ru: "Искусственные цветы", en: "Artificial flowers", cn: "仿真花", hs: "6702 90" },
      { seq: 29, ru: "Настольная лампа", en: "Table lamp", cn: "台燈", hs: "9405 29" },
    ],
  },
  {
    code: "PF-140000",
    ru: "Фото и видеотехника",
    en: "Photo and video equipment",
    cn: "照片和視頻設備",
    items: [
      { seq: 1, ru: "Фотоаппарат", en: "Camera", cn: "相機", hs: "8525 89" },
      { seq: 2, ru: "Зеркальный фотоаппарат", en: "DSLR camera", cn: "單反相機", hs: "8525 89" },
      { seq: 3, ru: "Объектив", en: "Camera lens", cn: "鏡頭", hs: "9002 11" },
      { seq: 4, ru: "Видеокамера", en: "Video camera", cn: "攝像機", hs: "8525 89" },
      { seq: 5, ru: "Экшн-камера", en: "Action camera", cn: "運動相機", hs: "8525 89" },
      { seq: 6, ru: "Штатив", en: "Tripod", cn: "三腳架", hs: "9620 00" },
      { seq: 7, ru: "Стабилизатор (стедикам)", en: "Gimbal stabilizer", cn: "穩定器", hs: "9620 00" },
      { seq: 8, ru: "Вспышка", en: "Camera flash", cn: "閃光燈", hs: "9006 61" },
      { seq: 9, ru: "Карта памяти", en: "Memory card", cn: "存儲卡", hs: "8523 51" },
      { seq: 10, ru: "Сумка для фотоаппарата", en: "Camera bag", cn: "相機包", hs: "4202 92" },
      { seq: 11, ru: "Фотофон", en: "Photo backdrop", cn: "攝影背景布", hs: "6307 90" },
      { seq: 12, ru: "Светодиодная панель для съёмки", en: "LED video light panel", cn: "攝影補光燈", hs: "9405 42" },
      { seq: 13, ru: "Кольцевая лампа", en: "Ring light", cn: "環形補光燈", hs: "9405 42" },
      { seq: 14, ru: "Микрофон", en: "Microphone", cn: "麥克風", hs: "8518 10" },
      { seq: 15, ru: "Петличный микрофон", en: "Lavalier microphone", cn: "領夾麥克風", hs: "8518 10" },
      { seq: 16, ru: "Фильтры для объектива", en: "Lens filters", cn: "鏡頭濾鏡", hs: "9002 20" },
      { seq: 17, ru: "Фотопринтер", en: "Photo printer", cn: "照片打印機", hs: "8443 32" },
      { seq: 18, ru: "Фотобумага", en: "Photo paper", cn: "相紙", hs: "3703 20" },
      { seq: 19, ru: "Аккумулятор для камеры", en: "Camera battery", cn: "相機電池", hs: "8507 60" },
      { seq: 20, ru: "Зарядное устройство", en: "Battery charger", cn: "充電器", hs: "8504 40" },
    ],
  },
  {
    code: "PF-150000",
    ru: "Электроника",
    en: "Electronics",
    cn: "電子產品",
    items: [
      { seq: 1, ru: "Смартфон", en: "Smartphone", cn: "智能手機", hs: "8517 13" },
      { seq: 2, ru: "Кнопочный телефон", en: "Feature phone", cn: "功能手機", hs: "8517 14" },
      { seq: 3, ru: "Планшет", en: "Tablet", cn: "平板電腦", hs: "8471 30" },
      { seq: 4, ru: "Умные часы", en: "Smartwatch", cn: "智能手錶", hs: "8517 62" },
      { seq: 5, ru: "Фитнес-браслет", en: "Fitness tracker", cn: "智能手環", hs: "8517 62" },
      { seq: 6, ru: "Наушники проводные", en: "Wired headphones", cn: "有線耳機", hs: "8518 30" },
      { seq: 7, ru: "Беспроводные наушники (TWS)", en: "Wireless earbuds (TWS)", cn: "無線藍牙耳機", hs: "8518 30" },
      { seq: 8, ru: "Портативная колонка", en: "Portable speaker", cn: "便攜音箱", hs: "8518 22" },
      { seq: 9, ru: "Умная колонка", en: "Smart speaker", cn: "智能音箱", hs: "8518 22" },
      { seq: 10, ru: "Power bank", en: "Power bank", cn: "充電寶", hs: "8507 60" },
      { seq: 11, ru: "Зарядное устройство / адаптер", en: "Charger / power adapter", cn: "充電器／電源適配器", hs: "8504 40" },
      { seq: 12, ru: "Кабель USB", en: "USB cable", cn: "USB 數據線", hs: "8544 42" },
      { seq: 13, ru: "Телевизор", en: "Television", cn: "電視機", hs: "8528 72" },
      { seq: 14, ru: "ТВ-приставка", en: "TV box / set-top box", cn: "電視盒子", hs: "8528 71" },
      { seq: 15, ru: "Электронная книга", en: "E-reader", cn: "電子書閱讀器", hs: "8543 70" },
      { seq: 16, ru: "Игровая приставка", en: "Game console", cn: "遊戲機", hs: "9504 50" },
      { seq: 17, ru: "Джойстик / геймпад", en: "Gamepad", cn: "遊戲手柄", hs: "9504 50" },
      { seq: 18, ru: "VR-очки", en: "VR headset", cn: "VR 眼鏡", hs: "8528 52" },
      { seq: 19, ru: "Квадрокоптер (дрон)", en: "Drone", cn: "無人機", hs: "8806 22" },
      { seq: 20, ru: "Электронная сигарета", en: "E-cigarette", cn: "電子煙", hs: "8543 40" },
      { seq: 21, ru: "Умная лампа", en: "Smart bulb", cn: "智能燈泡", hs: "8539 52" },
      { seq: 22, ru: "Портативный проектор", en: "Portable projector", cn: "便攜投影儀", hs: "8528 62" },
      { seq: 23, ru: "Чехол для телефона", en: "Phone case", cn: "手機殼", hs: "3926 90" },
      { seq: 24, ru: "Защитное стекло", en: "Screen protector", cn: "鋼化膜", hs: "3919 90" },
      { seq: 25, ru: "Селфи-палка", en: "Selfie stick", cn: "自拍桿", hs: "9620 00" },
    ],
  },
];

/** Плоский счётчик позиций (без секций) — для логов/проверок. */
export const PRODUCT_NAME_ITEM_COUNT = PRODUCT_NAME_SECTIONS.reduce(
  (sum, section) => sum + section.items.length,
  0
);
