import { prisma } from "../lib/prisma";

type CountrySeed = {
  code: string;
  nameRu: string;
  nameEn: string;
  phoneCode: string;
  phoneNumberMin: number;
  phoneNumberMax: number;
  postalCodeRegex: string | null;
  postalCodeExample: string | null;
  aliases: string | null;
};

// Полный справочник стран мира (ISO 3166-1 alpha-2): суверенные государства
// + основные зависимые территории. Длины номеров (phoneNumberMin/Max) даны
// с запасом там, где формат переменный, чтобы не было ложных блокировок.
const COUNTRIES: CountrySeed[] = [
  { code: "AD", nameRu: "Андорра", nameEn: "Andorra", phoneCode: "+376", phoneNumberMin: 6, phoneNumberMax: 9, postalCodeRegex: "^AD[0-9]{3}$", postalCodeExample: "AD500", aliases: null },
  { code: "AE", nameRu: "ОАЭ", nameEn: "United Arab Emirates", phoneCode: "+971", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: "Эмираты,Объединённые Арабские Эмираты,UAE,Emirates" },
  { code: "AF", nameRu: "Афганистан", nameEn: "Afghanistan", phoneCode: "+93", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1001", aliases: null },
  { code: "AG", nameRu: "Антигуа и Барбуда", nameEn: "Antigua and Barbuda", phoneCode: "+1268", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "AI", nameRu: "Ангилья", nameEn: "Anguilla", phoneCode: "+1264", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^AI-2640$", postalCodeExample: "AI-2640", aliases: null },
  { code: "AL", nameRu: "Албания", nameEn: "Albania", phoneCode: "+355", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1001", aliases: null },
  { code: "AM", nameRu: "Армения", nameEn: "Armenia", phoneCode: "+374", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "0010", aliases: null },
  { code: "AO", nameRu: "Ангола", nameEn: "Angola", phoneCode: "+244", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "AR", nameRu: "Аргентина", nameEn: "Argentina", phoneCode: "+54", phoneNumberMin: 10, phoneNumberMax: 11, postalCodeRegex: "^[A-Z]?[0-9]{4}[A-Z]{0,3}$", postalCodeExample: "C1425", aliases: null },
  { code: "AS", nameRu: "Американское Самоа", nameEn: "American Samoa", phoneCode: "+1684", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}(-[0-9]{4})?$", postalCodeExample: "96799", aliases: null },
  { code: "AT", nameRu: "Австрия", nameEn: "Austria", phoneCode: "+43", phoneNumberMin: 6, phoneNumberMax: 13, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1010", aliases: null },
  { code: "AU", nameRu: "Австралия", nameEn: "Australia", phoneCode: "+61", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "2000", aliases: null },
  { code: "AW", nameRu: "Аруба", nameEn: "Aruba", phoneCode: "+297", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "AX", nameRu: "Аландские острова", nameEn: "Åland Islands", phoneCode: "+358", phoneNumberMin: 6, phoneNumberMax: 12, postalCodeRegex: "^22[0-9]{3}$", postalCodeExample: "22100", aliases: "Аланды" },
  { code: "AZ", nameRu: "Азербайджан", nameEn: "Azerbaijan", phoneCode: "+994", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^(AZ )?[0-9]{4}$", postalCodeExample: "AZ 1000", aliases: null },
  { code: "BA", nameRu: "Босния и Герцеговина", nameEn: "Bosnia and Herzegovina", phoneCode: "+387", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "71000", aliases: "Босния" },
  { code: "BB", nameRu: "Барбадос", nameEn: "Barbados", phoneCode: "+1246", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^BB[0-9]{5}$", postalCodeExample: "BB11000", aliases: null },
  { code: "BD", nameRu: "Бангладеш", nameEn: "Bangladesh", phoneCode: "+880", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "BE", nameRu: "Бельгия", nameEn: "Belgium", phoneCode: "+32", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "BF", nameRu: "Буркина-Фасо", nameEn: "Burkina Faso", phoneCode: "+226", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "BG", nameRu: "Болгария", nameEn: "Bulgaria", phoneCode: "+359", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "BH", nameRu: "Бахрейн", nameEn: "Bahrain", phoneCode: "+973", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{3,4}$", postalCodeExample: "199", aliases: null },
  { code: "BI", nameRu: "Бурунди", nameEn: "Burundi", phoneCode: "+257", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "BJ", nameRu: "Бенин", nameEn: "Benin", phoneCode: "+229", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "BL", nameRu: "Сен-Бартелеми", nameEn: "Saint Barthélemy", phoneCode: "+590", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^97133$", postalCodeExample: "97133", aliases: null },
  { code: "BM", nameRu: "Бермудские острова", nameEn: "Bermuda", phoneCode: "+1441", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[A-Z]{2} ?[0-9A-Z]{2}$", postalCodeExample: "CR 03", aliases: "Бермуды" },
  { code: "BN", nameRu: "Бруней", nameEn: "Brunei", phoneCode: "+673", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: "^[A-Z]{2}[0-9]{4}$", postalCodeExample: "BS8811", aliases: null },
  { code: "BO", nameRu: "Боливия", nameEn: "Bolivia", phoneCode: "+591", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "BQ", nameRu: "Бонэйр, Синт-Эстатиус и Саба", nameEn: "Caribbean Netherlands", phoneCode: "+599", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: "Бонэйр" },
  { code: "BR", nameRu: "Бразилия", nameEn: "Brazil", phoneCode: "+55", phoneNumberMin: 10, phoneNumberMax: 11, postalCodeRegex: "^[0-9]{5}-?[0-9]{3}$", postalCodeExample: "01310-100", aliases: null },
  { code: "BS", nameRu: "Багамские острова", nameEn: "Bahamas", phoneCode: "+1242", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: "Багамы" },
  { code: "BT", nameRu: "Бутан", nameEn: "Bhutan", phoneCode: "+975", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11001", aliases: null },
  { code: "BW", nameRu: "Ботсвана", nameEn: "Botswana", phoneCode: "+267", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "BY", nameRu: "Беларусь", nameEn: "Belarus", phoneCode: "+375", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "220000", aliases: "Белоруссия" },
  { code: "BZ", nameRu: "Белиз", nameEn: "Belize", phoneCode: "+501", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "CA", nameRu: "Канада", nameEn: "Canada", phoneCode: "+1", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]$", postalCodeExample: "M5V 3L9", aliases: null },
  { code: "CC", nameRu: "Кокосовые острова", nameEn: "Cocos (Keeling) Islands", phoneCode: "+61", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "6799", aliases: null },
  { code: "CD", nameRu: "ДР Конго", nameEn: "DR Congo", phoneCode: "+243", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: "Демократическая Республика Конго,Конго-Киншаса,Заир" },
  { code: "CF", nameRu: "ЦАР", nameEn: "Central African Republic", phoneCode: "+236", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: "Центральноафриканская Республика" },
  { code: "CG", nameRu: "Республика Конго", nameEn: "Republic of the Congo", phoneCode: "+242", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: "Конго-Браззавиль,Конго" },
  { code: "CH", nameRu: "Швейцария", nameEn: "Switzerland", phoneCode: "+41", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "8001", aliases: null },
  { code: "CI", nameRu: "Кот-д’Ивуар", nameEn: "Côte d'Ivoire", phoneCode: "+225", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: "Берег Слоновой Кости,Ivory Coast" },
  { code: "CK", nameRu: "Острова Кука", nameEn: "Cook Islands", phoneCode: "+682", phoneNumberMin: 5, phoneNumberMax: 5, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "CL", nameRu: "Чили", nameEn: "Chile", phoneCode: "+56", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{7}$", postalCodeExample: "8320000", aliases: null },
  { code: "CM", nameRu: "Камерун", nameEn: "Cameroon", phoneCode: "+237", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "CN", nameRu: "Китай", nameEn: "China", phoneCode: "+86", phoneNumberMin: 7, phoneNumberMax: 11, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "100000", aliases: "КНР,Китайская Народная Республика" },
  { code: "CO", nameRu: "Колумбия", nameEn: "Colombia", phoneCode: "+57", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "110111", aliases: null },
  { code: "CR", nameRu: "Коста-Рика", nameEn: "Costa Rica", phoneCode: "+506", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10101", aliases: null },
  { code: "CU", nameRu: "Куба", nameEn: "Cuba", phoneCode: "+53", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10400", aliases: null },
  { code: "CV", nameRu: "Кабо-Верде", nameEn: "Cape Verde", phoneCode: "+238", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: "Острова Зелёного Мыса" },
  { code: "CW", nameRu: "Кюрасао", nameEn: "Curaçao", phoneCode: "+599", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "CX", nameRu: "Остров Рождества", nameEn: "Christmas Island", phoneCode: "+61", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "6798", aliases: null },
  { code: "CY", nameRu: "Кипр", nameEn: "Cyprus", phoneCode: "+357", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1010", aliases: null },
  { code: "CZ", nameRu: "Чехия", nameEn: "Czechia", phoneCode: "+420", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{3} ?[0-9]{2}$", postalCodeExample: "110 00", aliases: "Чешская Республика,Czech Republic" },
  { code: "DE", nameRu: "Германия", nameEn: "Germany", phoneCode: "+49", phoneNumberMin: 6, phoneNumberMax: 11, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10115", aliases: "ФРГ,Deutschland" },
  { code: "DJ", nameRu: "Джибути", nameEn: "Djibouti", phoneCode: "+253", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "DK", nameRu: "Дания", nameEn: "Denmark", phoneCode: "+45", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1050", aliases: null },
  { code: "DM", nameRu: "Доминика", nameEn: "Dominica", phoneCode: "+1767", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "DO", nameRu: "Доминиканская Республика", nameEn: "Dominican Republic", phoneCode: "+1809", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10101", aliases: null },
  { code: "DZ", nameRu: "Алжир", nameEn: "Algeria", phoneCode: "+213", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "16000", aliases: null },
  { code: "EC", nameRu: "Эквадор", nameEn: "Ecuador", phoneCode: "+593", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "170150", aliases: null },
  { code: "EE", nameRu: "Эстония", nameEn: "Estonia", phoneCode: "+372", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10111", aliases: null },
  { code: "EG", nameRu: "Египет", nameEn: "Egypt", phoneCode: "+20", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11511", aliases: null },
  { code: "EH", nameRu: "Западная Сахара", nameEn: "Western Sahara", phoneCode: "+212", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "ER", nameRu: "Эритрея", nameEn: "Eritrea", phoneCode: "+291", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "ES", nameRu: "Испания", nameEn: "Spain", phoneCode: "+34", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "28013", aliases: null },
  { code: "ET", nameRu: "Эфиопия", nameEn: "Ethiopia", phoneCode: "+251", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "FI", nameRu: "Финляндия", nameEn: "Finland", phoneCode: "+358", phoneNumberMin: 6, phoneNumberMax: 12, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "00100", aliases: null },
  { code: "FJ", nameRu: "Фиджи", nameEn: "Fiji", phoneCode: "+679", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "FK", nameRu: "Фолклендские острова", nameEn: "Falkland Islands", phoneCode: "+500", phoneNumberMin: 5, phoneNumberMax: 5, postalCodeRegex: "^FIQQ 1ZZ$", postalCodeExample: "FIQQ 1ZZ", aliases: null },
  { code: "FM", nameRu: "Микронезия", nameEn: "Micronesia", phoneCode: "+691", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: "^[0-9]{5}(-[0-9]{4})?$", postalCodeExample: "96941", aliases: null },
  { code: "FO", nameRu: "Фарерские острова", nameEn: "Faroe Islands", phoneCode: "+298", phoneNumberMin: 6, phoneNumberMax: 6, postalCodeRegex: "^[0-9]{3}$", postalCodeExample: "100", aliases: "Фареры" },
  { code: "FR", nameRu: "Франция", nameEn: "France", phoneCode: "+33", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "75001", aliases: null },
  { code: "GA", nameRu: "Габон", nameEn: "Gabon", phoneCode: "+241", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "GB", nameRu: "Великобритания", nameEn: "United Kingdom", phoneCode: "+44", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$", postalCodeExample: "SW1A 1AA", aliases: "Англия,UK,Britain,United Kingdom of Great Britain,Соединённое Королевство" },
  { code: "GD", nameRu: "Гренада", nameEn: "Grenada", phoneCode: "+1473", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "GE", nameRu: "Грузия", nameEn: "Georgia", phoneCode: "+995", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "0100", aliases: null },
  { code: "GF", nameRu: "Французская Гвиана", nameEn: "French Guiana", phoneCode: "+594", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^973[0-9]{2}$", postalCodeExample: "97300", aliases: null },
  { code: "GG", nameRu: "Гернси", nameEn: "Guernsey", phoneCode: "+44", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^GY[0-9] ?[0-9][A-Z]{2}$", postalCodeExample: "GY1 1AA", aliases: null },
  { code: "GH", nameRu: "Гана", nameEn: "Ghana", phoneCode: "+233", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "GI", nameRu: "Гибралтар", nameEn: "Gibraltar", phoneCode: "+350", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^GX11 1AA$", postalCodeExample: "GX11 1AA", aliases: null },
  { code: "GL", nameRu: "Гренландия", nameEn: "Greenland", phoneCode: "+299", phoneNumberMin: 6, phoneNumberMax: 6, postalCodeRegex: "^39[0-9]{2}$", postalCodeExample: "3900", aliases: null },
  { code: "GM", nameRu: "Гамбия", nameEn: "Gambia", phoneCode: "+220", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "GN", nameRu: "Гвинея", nameEn: "Guinea", phoneCode: "+224", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "GP", nameRu: "Гваделупа", nameEn: "Guadeloupe", phoneCode: "+590", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^971[0-9]{2}$", postalCodeExample: "97100", aliases: null },
  { code: "GQ", nameRu: "Экваториальная Гвинея", nameEn: "Equatorial Guinea", phoneCode: "+240", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "GR", nameRu: "Греция", nameEn: "Greece", phoneCode: "+30", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{3} ?[0-9]{2}$", postalCodeExample: "104 31", aliases: null },
  { code: "GT", nameRu: "Гватемала", nameEn: "Guatemala", phoneCode: "+502", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "01001", aliases: null },
  { code: "GU", nameRu: "Гуам", nameEn: "Guam", phoneCode: "+1671", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}(-[0-9]{4})?$", postalCodeExample: "96910", aliases: null },
  { code: "GW", nameRu: "Гвинея-Бисау", nameEn: "Guinea-Bissau", phoneCode: "+245", phoneNumberMin: 7, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "GY", nameRu: "Гайана", nameEn: "Guyana", phoneCode: "+592", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "HK", nameRu: "Гонконг", nameEn: "Hong Kong", phoneCode: "+852", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: "Hong Kong,Сянган" },
  { code: "HN", nameRu: "Гондурас", nameEn: "Honduras", phoneCode: "+504", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11101", aliases: null },
  { code: "HR", nameRu: "Хорватия", nameEn: "Croatia", phoneCode: "+385", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10000", aliases: null },
  { code: "HT", nameRu: "Гаити", nameEn: "Haiti", phoneCode: "+509", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^HT[0-9]{4}$", postalCodeExample: "HT1110", aliases: null },
  { code: "HU", nameRu: "Венгрия", nameEn: "Hungary", phoneCode: "+36", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1011", aliases: null },
  { code: "ID", nameRu: "Индонезия", nameEn: "Indonesia", phoneCode: "+62", phoneNumberMin: 8, phoneNumberMax: 12, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10110", aliases: null },
  { code: "IE", nameRu: "Ирландия", nameEn: "Ireland", phoneCode: "+353", phoneNumberMin: 7, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: "D02 AF30", aliases: null },
  { code: "IL", nameRu: "Израиль", nameEn: "Israel", phoneCode: "+972", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}([0-9]{2})?$", postalCodeExample: "9103401", aliases: null },
  { code: "IM", nameRu: "Остров Мэн", nameEn: "Isle of Man", phoneCode: "+44", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^IM[0-9] ?[0-9][A-Z]{2}$", postalCodeExample: "IM1 1AA", aliases: null },
  { code: "IN", nameRu: "Индия", nameEn: "India", phoneCode: "+91", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "110001", aliases: null },
  { code: "IO", nameRu: "Британская территория в Индийском океане", nameEn: "British Indian Ocean Territory", phoneCode: "+246", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: "^BBND 1ZZ$", postalCodeExample: "BBND 1ZZ", aliases: null },
  { code: "IQ", nameRu: "Ирак", nameEn: "Iraq", phoneCode: "+964", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10001", aliases: null },
  { code: "IR", nameRu: "Иран", nameEn: "Iran", phoneCode: "+98", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{10}$", postalCodeExample: "1111111111", aliases: null },
  { code: "IS", nameRu: "Исландия", nameEn: "Iceland", phoneCode: "+354", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: "^[0-9]{3}$", postalCodeExample: "101", aliases: null },
  { code: "IT", nameRu: "Италия", nameEn: "Italy", phoneCode: "+39", phoneNumberMin: 6, phoneNumberMax: 11, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "00100", aliases: null },
  { code: "JE", nameRu: "Джерси", nameEn: "Jersey", phoneCode: "+44", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^JE[0-9] ?[0-9][A-Z]{2}$", postalCodeExample: "JE1 1AA", aliases: null },
  { code: "JM", nameRu: "Ямайка", nameEn: "Jamaica", phoneCode: "+1876", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "JO", nameRu: "Иордания", nameEn: "Jordan", phoneCode: "+962", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11118", aliases: null },
  { code: "JP", nameRu: "Япония", nameEn: "Japan", phoneCode: "+81", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{3}-[0-9]{4}$", postalCodeExample: "100-0001", aliases: null },
  { code: "KE", nameRu: "Кения", nameEn: "Kenya", phoneCode: "+254", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "00100", aliases: null },
  { code: "KG", nameRu: "Киргизия", nameEn: "Kyrgyzstan", phoneCode: "+996", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "720000", aliases: "Кыргызстан" },
  { code: "KH", nameRu: "Камбоджа", nameEn: "Cambodia", phoneCode: "+855", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5,6}$", postalCodeExample: "120101", aliases: null },
  { code: "KI", nameRu: "Кирибати", nameEn: "Kiribati", phoneCode: "+686", phoneNumberMin: 5, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "KM", nameRu: "Коморы", nameEn: "Comoros", phoneCode: "+269", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: "Коморские Острова" },
  { code: "KN", nameRu: "Сент-Китс и Невис", nameEn: "Saint Kitts and Nevis", phoneCode: "+1869", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "KP", nameRu: "КНДР", nameEn: "North Korea", phoneCode: "+850", phoneNumberMin: 6, phoneNumberMax: 13, postalCodeRegex: null, postalCodeExample: null, aliases: "Северная Корея,North Korea" },
  { code: "KR", nameRu: "Республика Корея", nameEn: "South Korea", phoneCode: "+82", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "03187", aliases: "Южная Корея,South Korea,Корея" },
  { code: "KW", nameRu: "Кувейт", nameEn: "Kuwait", phoneCode: "+965", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "12345", aliases: null },
  { code: "KY", nameRu: "Острова Кайман", nameEn: "Cayman Islands", phoneCode: "+1345", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^KY[0-9]-[0-9]{4}$", postalCodeExample: "KY1-1001", aliases: "Каймановы острова" },
  { code: "KZ", nameRu: "Казахстан", nameEn: "Kazakhstan", phoneCode: "+7", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "010000", aliases: null },
  { code: "LA", nameRu: "Лаос", nameEn: "Laos", phoneCode: "+856", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "01000", aliases: null },
  { code: "LB", nameRu: "Ливан", nameEn: "Lebanon", phoneCode: "+961", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4} ?[0-9]{4}$", postalCodeExample: "1103 2010", aliases: null },
  { code: "LC", nameRu: "Сент-Люсия", nameEn: "Saint Lucia", phoneCode: "+1758", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^LC[0-9]{2} ?[0-9]{3}$", postalCodeExample: "LC01 101", aliases: null },
  { code: "LI", nameRu: "Лихтенштейн", nameEn: "Liechtenstein", phoneCode: "+423", phoneNumberMin: 7, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "9490", aliases: null },
  { code: "LK", nameRu: "Шри-Ланка", nameEn: "Sri Lanka", phoneCode: "+94", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10000", aliases: null },
  { code: "LR", nameRu: "Либерия", nameEn: "Liberia", phoneCode: "+231", phoneNumberMin: 7, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "LS", nameRu: "Лесото", nameEn: "Lesotho", phoneCode: "+266", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{3}$", postalCodeExample: "100", aliases: null },
  { code: "LT", nameRu: "Литва", nameEn: "Lithuania", phoneCode: "+370", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^(LT-)?[0-9]{5}$", postalCodeExample: "LT-01100", aliases: null },
  { code: "LU", nameRu: "Люксембург", nameEn: "Luxembourg", phoneCode: "+352", phoneNumberMin: 6, phoneNumberMax: 11, postalCodeRegex: "^(L-)?[0-9]{4}$", postalCodeExample: "L-1009", aliases: null },
  { code: "LV", nameRu: "Латвия", nameEn: "Latvia", phoneCode: "+371", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^(LV-)?[0-9]{4}$", postalCodeExample: "LV-1050", aliases: null },
  { code: "LY", nameRu: "Ливия", nameEn: "Libya", phoneCode: "+218", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "MA", nameRu: "Марокко", nameEn: "Morocco", phoneCode: "+212", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10000", aliases: null },
  { code: "MC", nameRu: "Монако", nameEn: "Monaco", phoneCode: "+377", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^980[0-9]{2}$", postalCodeExample: "98000", aliases: null },
  { code: "MD", nameRu: "Молдова", nameEn: "Moldova", phoneCode: "+373", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^(MD-?)?[0-9]{4}$", postalCodeExample: "MD-2001", aliases: "Молдавия" },
  { code: "ME", nameRu: "Черногория", nameEn: "Montenegro", phoneCode: "+382", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "81000", aliases: null },
  { code: "MF", nameRu: "Сен-Мартен", nameEn: "Saint Martin", phoneCode: "+590", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^97150$", postalCodeExample: "97150", aliases: null },
  { code: "MG", nameRu: "Мадагаскар", nameEn: "Madagascar", phoneCode: "+261", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{3}$", postalCodeExample: "101", aliases: null },
  { code: "MH", nameRu: "Маршалловы Острова", nameEn: "Marshall Islands", phoneCode: "+692", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: "^[0-9]{5}(-[0-9]{4})?$", postalCodeExample: "96960", aliases: null },
  { code: "MK", nameRu: "Северная Македония", nameEn: "North Macedonia", phoneCode: "+389", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: "Македония" },
  { code: "ML", nameRu: "Мали", nameEn: "Mali", phoneCode: "+223", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "MM", nameRu: "Мьянма", nameEn: "Myanmar", phoneCode: "+95", phoneNumberMin: 7, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11181", aliases: "Бирма,Burma" },
  { code: "MN", nameRu: "Монголия", nameEn: "Mongolia", phoneCode: "+976", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "14200", aliases: null },
  { code: "MO", nameRu: "Макао", nameEn: "Macau", phoneCode: "+853", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: "Аомынь,Macao" },
  { code: "MP", nameRu: "Северные Марианские острова", nameEn: "Northern Mariana Islands", phoneCode: "+1670", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}(-[0-9]{4})?$", postalCodeExample: "96950", aliases: null },
  { code: "MQ", nameRu: "Мартиника", nameEn: "Martinique", phoneCode: "+596", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^972[0-9]{2}$", postalCodeExample: "97200", aliases: null },
  { code: "MR", nameRu: "Мавритания", nameEn: "Mauritania", phoneCode: "+222", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "MS", nameRu: "Монтсеррат", nameEn: "Montserrat", phoneCode: "+1664", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^MSR ?[0-9]{4}$", postalCodeExample: "MSR1110", aliases: null },
  { code: "MT", nameRu: "Мальта", nameEn: "Malta", phoneCode: "+356", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[A-Z]{3} ?[0-9]{4}$", postalCodeExample: "VLT 1117", aliases: null },
  { code: "MU", nameRu: "Маврикий", nameEn: "Mauritius", phoneCode: "+230", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: "^[0-9A-Z][0-9]{4}$", postalCodeExample: "11324", aliases: null },
  { code: "MV", nameRu: "Мальдивы", nameEn: "Maldives", phoneCode: "+960", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "20026", aliases: null },
  { code: "MW", nameRu: "Малави", nameEn: "Malawi", phoneCode: "+265", phoneNumberMin: 7, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "MX", nameRu: "Мексика", nameEn: "Mexico", phoneCode: "+52", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "06000", aliases: null },
  { code: "MY", nameRu: "Малайзия", nameEn: "Malaysia", phoneCode: "+60", phoneNumberMin: 7, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "50000", aliases: null },
  { code: "MZ", nameRu: "Мозамбик", nameEn: "Mozambique", phoneCode: "+258", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1100", aliases: null },
  { code: "NA", nameRu: "Намибия", nameEn: "Namibia", phoneCode: "+264", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "NC", nameRu: "Новая Каледония", nameEn: "New Caledonia", phoneCode: "+687", phoneNumberMin: 6, phoneNumberMax: 6, postalCodeRegex: "^988[0-9]{2}$", postalCodeExample: "98800", aliases: null },
  { code: "NE", nameRu: "Нигер", nameEn: "Niger", phoneCode: "+227", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "8001", aliases: null },
  { code: "NF", nameRu: "Остров Норфолк", nameEn: "Norfolk Island", phoneCode: "+672", phoneNumberMin: 6, phoneNumberMax: 6, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "2899", aliases: null },
  { code: "NG", nameRu: "Нигерия", nameEn: "Nigeria", phoneCode: "+234", phoneNumberMin: 7, phoneNumberMax: 11, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "100001", aliases: null },
  { code: "NI", nameRu: "Никарагуа", nameEn: "Nicaragua", phoneCode: "+505", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10000", aliases: null },
  { code: "NL", nameRu: "Нидерланды", nameEn: "Netherlands", phoneCode: "+31", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4} ?[A-Z]{2}$", postalCodeExample: "1011 AB", aliases: "Голландия,Holland" },
  { code: "NO", nameRu: "Норвегия", nameEn: "Norway", phoneCode: "+47", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "0150", aliases: null },
  { code: "NP", nameRu: "Непал", nameEn: "Nepal", phoneCode: "+977", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "44600", aliases: null },
  { code: "NR", nameRu: "Науру", nameEn: "Nauru", phoneCode: "+674", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "NU", nameRu: "Ниуэ", nameEn: "Niue", phoneCode: "+683", phoneNumberMin: 4, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "NY", nameRu: "США (Нью-Йорк)", nameEn: "USA (New York)", phoneCode: "+1", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^1[0-9]{4}$", postalCodeExample: "10001", aliases: null },
  { code: "NZ", nameRu: "Новая Зеландия", nameEn: "New Zealand", phoneCode: "+64", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "6011", aliases: null },
  { code: "OM", nameRu: "Оман", nameEn: "Oman", phoneCode: "+968", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{3}$", postalCodeExample: "112", aliases: null },
  { code: "PA", nameRu: "Панама", nameEn: "Panama", phoneCode: "+507", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "0801", aliases: null },
  { code: "PE", nameRu: "Перу", nameEn: "Peru", phoneCode: "+51", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "15001", aliases: null },
  { code: "PF", nameRu: "Французская Полинезия", nameEn: "French Polynesia", phoneCode: "+689", phoneNumberMin: 6, phoneNumberMax: 8, postalCodeRegex: "^987[0-9]{2}$", postalCodeExample: "98700", aliases: null },
  { code: "PG", nameRu: "Папуа — Новая Гвинея", nameEn: "Papua New Guinea", phoneCode: "+675", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{3}$", postalCodeExample: "111", aliases: null },
  { code: "PH", nameRu: "Филиппины", nameEn: "Philippines", phoneCode: "+63", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "PK", nameRu: "Пакистан", nameEn: "Pakistan", phoneCode: "+92", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "44000", aliases: null },
  { code: "PL", nameRu: "Польша", nameEn: "Poland", phoneCode: "+48", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{2}-[0-9]{3}$", postalCodeExample: "00-001", aliases: null },
  { code: "PM", nameRu: "Сен-Пьер и Микелон", nameEn: "Saint Pierre and Miquelon", phoneCode: "+508", phoneNumberMin: 6, phoneNumberMax: 6, postalCodeRegex: "^97500$", postalCodeExample: "97500", aliases: null },
  { code: "PN", nameRu: "Острова Питкэрн", nameEn: "Pitcairn Islands", phoneCode: "+64", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: "^PCRN 1ZZ$", postalCodeExample: "PCRN 1ZZ", aliases: null },
  { code: "PR", nameRu: "Пуэрто-Рико", nameEn: "Puerto Rico", phoneCode: "+1787", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}(-[0-9]{4})?$", postalCodeExample: "00901", aliases: null },
  { code: "PS", nameRu: "Палестина", nameEn: "Palestine", phoneCode: "+970", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "PT", nameRu: "Португалия", nameEn: "Portugal", phoneCode: "+351", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}-[0-9]{3}$", postalCodeExample: "1000-001", aliases: null },
  { code: "PW", nameRu: "Палау", nameEn: "Palau", phoneCode: "+680", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "96940", aliases: null },
  { code: "PY", nameRu: "Парагвай", nameEn: "Paraguay", phoneCode: "+595", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1101", aliases: null },
  { code: "QA", nameRu: "Катар", nameEn: "Qatar", phoneCode: "+974", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "RE", nameRu: "Реюньон", nameEn: "Réunion", phoneCode: "+262", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^974[0-9]{2}$", postalCodeExample: "97400", aliases: null },
  { code: "RO", nameRu: "Румыния", nameEn: "Romania", phoneCode: "+40", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "010001", aliases: null },
  { code: "RS", nameRu: "Сербия", nameEn: "Serbia", phoneCode: "+381", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11000", aliases: null },
  { code: "RU", nameRu: "Россия", nameEn: "Russia", phoneCode: "+7", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "101000", aliases: "РФ,Российская Федерация,Russian Federation" },
  { code: "RW", nameRu: "Руанда", nameEn: "Rwanda", phoneCode: "+250", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "SA", nameRu: "Саудовская Аравия", nameEn: "Saudi Arabia", phoneCode: "+966", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11564", aliases: null },
  { code: "SB", nameRu: "Соломоновы Острова", nameEn: "Solomon Islands", phoneCode: "+677", phoneNumberMin: 5, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "SC", nameRu: "Сейшельские Острова", nameEn: "Seychelles", phoneCode: "+248", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: "Сейшелы" },
  { code: "SD", nameRu: "Судан", nameEn: "Sudan", phoneCode: "+249", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11111", aliases: null },
  { code: "SE", nameRu: "Швеция", nameEn: "Sweden", phoneCode: "+46", phoneNumberMin: 7, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{3} ?[0-9]{2}$", postalCodeExample: "111 20", aliases: null },
  { code: "SG", nameRu: "Сингапур", nameEn: "Singapore", phoneCode: "+65", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "238858", aliases: null },
  { code: "SH", nameRu: "Остров Святой Елены", nameEn: "Saint Helena", phoneCode: "+290", phoneNumberMin: 4, phoneNumberMax: 5, postalCodeRegex: "^(STHL|ASCN|TDCU) 1ZZ$", postalCodeExample: "STHL 1ZZ", aliases: null },
  { code: "SI", nameRu: "Словения", nameEn: "Slovenia", phoneCode: "+386", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "SJ", nameRu: "Шпицберген и Ян-Майен", nameEn: "Svalbard and Jan Mayen", phoneCode: "+47", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "9170", aliases: "Шпицберген" },
  { code: "SK", nameRu: "Словакия", nameEn: "Slovakia", phoneCode: "+421", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{3} ?[0-9]{2}$", postalCodeExample: "811 01", aliases: null },
  { code: "SL", nameRu: "Сьерра-Леоне", nameEn: "Sierra Leone", phoneCode: "+232", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "SM", nameRu: "Сан-Марино", nameEn: "San Marino", phoneCode: "+378", phoneNumberMin: 6, phoneNumberMax: 10, postalCodeRegex: "^4789[0-9]$", postalCodeExample: "47890", aliases: null },
  { code: "SN", nameRu: "Сенегал", nameEn: "Senegal", phoneCode: "+221", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10200", aliases: null },
  { code: "SO", nameRu: "Сомали", nameEn: "Somalia", phoneCode: "+252", phoneNumberMin: 7, phoneNumberMax: 9, postalCodeRegex: "^[A-Z]{2} ?[0-9]{5}$", postalCodeExample: "JH 09010", aliases: null },
  { code: "SR", nameRu: "Суринам", nameEn: "Suriname", phoneCode: "+597", phoneNumberMin: 6, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "SS", nameRu: "Южный Судан", nameEn: "South Sudan", phoneCode: "+211", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "ST", nameRu: "Сан-Томе и Принсипи", nameEn: "São Tomé and Príncipe", phoneCode: "+239", phoneNumberMin: 7, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "SV", nameRu: "Сальвадор", nameEn: "El Salvador", phoneCode: "+503", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1101", aliases: null },
  { code: "SX", nameRu: "Синт-Мартен", nameEn: "Sint Maarten", phoneCode: "+1721", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "SY", nameRu: "Сирия", nameEn: "Syria", phoneCode: "+963", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "SZ", nameRu: "Эсватини", nameEn: "Eswatini", phoneCode: "+268", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: "^[A-Z][0-9]{3}$", postalCodeExample: "H100", aliases: "Свазиленд" },
  { code: "TC", nameRu: "Тёркс и Кайкос", nameEn: "Turks and Caicos Islands", phoneCode: "+1649", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^TKCA 1ZZ$", postalCodeExample: "TKCA 1ZZ", aliases: null },
  { code: "TD", nameRu: "Чад", nameEn: "Chad", phoneCode: "+235", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "TG", nameRu: "Того", nameEn: "Togo", phoneCode: "+228", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "TH", nameRu: "Таиланд", nameEn: "Thailand", phoneCode: "+66", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10100", aliases: null },
  { code: "TJ", nameRu: "Таджикистан", nameEn: "Tajikistan", phoneCode: "+992", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "734000", aliases: null },
  { code: "TK", nameRu: "Токелау", nameEn: "Tokelau", phoneCode: "+690", phoneNumberMin: 4, phoneNumberMax: 5, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "TL", nameRu: "Восточный Тимор", nameEn: "Timor-Leste", phoneCode: "+670", phoneNumberMin: 7, phoneNumberMax: 8, postalCodeRegex: null, postalCodeExample: null, aliases: "Тимор-Лешти" },
  { code: "TM", nameRu: "Туркмения", nameEn: "Turkmenistan", phoneCode: "+993", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "744000", aliases: "Туркменистан" },
  { code: "TN", nameRu: "Тунис", nameEn: "Tunisia", phoneCode: "+216", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1000", aliases: null },
  { code: "TO", nameRu: "Тонга", nameEn: "Tonga", phoneCode: "+676", phoneNumberMin: 5, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "TR", nameRu: "Турция", nameEn: "Turkey", phoneCode: "+90", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "34000", aliases: "Türkiye" },
  { code: "TT", nameRu: "Тринидад и Тобаго", nameEn: "Trinidad and Tobago", phoneCode: "+1868", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "120110", aliases: null },
  { code: "TV", nameRu: "Тувалу", nameEn: "Tuvalu", phoneCode: "+688", phoneNumberMin: 5, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "TW", nameRu: "Тайвань", nameEn: "Taiwan", phoneCode: "+886", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{3}([0-9]{2,3})?$", postalCodeExample: "100", aliases: null },
  { code: "TZ", nameRu: "Танзания", nameEn: "Tanzania", phoneCode: "+255", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11101", aliases: null },
  { code: "UA", nameRu: "Украина", nameEn: "Ukraine", phoneCode: "+380", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "01001", aliases: null },
  { code: "UG", nameRu: "Уганда", nameEn: "Uganda", phoneCode: "+256", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "US", nameRu: "США", nameEn: "United States", phoneCode: "+1", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}(-[0-9]{4})?$", postalCodeExample: "10001", aliases: "Соединённые Штаты,USA,Америка,United States of America,Штаты" },
  { code: "UY", nameRu: "Уругвай", nameEn: "Uruguay", phoneCode: "+598", phoneNumberMin: 8, phoneNumberMax: 8, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "11000", aliases: null },
  { code: "UZ", nameRu: "Узбекистан", nameEn: "Uzbekistan", phoneCode: "+998", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "100000", aliases: null },
  { code: "VA", nameRu: "Ватикан", nameEn: "Vatican City", phoneCode: "+379", phoneNumberMin: 6, phoneNumberMax: 11, postalCodeRegex: "^00120$", postalCodeExample: "00120", aliases: "Святой Престол,Holy See" },
  { code: "VC", nameRu: "Сент-Винсент и Гренадины", nameEn: "Saint Vincent and the Grenadines", phoneCode: "+1784", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^VC[0-9]{4}$", postalCodeExample: "VC0100", aliases: null },
  { code: "VE", nameRu: "Венесуэла", nameEn: "Venezuela", phoneCode: "+58", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "1010", aliases: null },
  { code: "VG", nameRu: "Британские Виргинские острова", nameEn: "British Virgin Islands", phoneCode: "+1284", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^VG[0-9]{4}$", postalCodeExample: "VG1110", aliases: null },
  { code: "VI", nameRu: "Виргинские острова (США)", nameEn: "U.S. Virgin Islands", phoneCode: "+1340", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{5}(-[0-9]{4})?$", postalCodeExample: "00801", aliases: null },
  { code: "VN", nameRu: "Вьетнам", nameEn: "Vietnam", phoneCode: "+84", phoneNumberMin: 9, phoneNumberMax: 10, postalCodeRegex: "^[0-9]{6}$", postalCodeExample: "100000", aliases: null },
  { code: "VT", nameRu: "США (Вермонт)", nameEn: "USA (Vermont)", phoneCode: "+1", phoneNumberMin: 10, phoneNumberMax: 10, postalCodeRegex: "^05[0-9]{3}$", postalCodeExample: "05001", aliases: null },
  { code: "VU", nameRu: "Вануату", nameEn: "Vanuatu", phoneCode: "+678", phoneNumberMin: 5, phoneNumberMax: 7, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "WF", nameRu: "Уоллис и Футуна", nameEn: "Wallis and Futuna", phoneCode: "+681", phoneNumberMin: 6, phoneNumberMax: 6, postalCodeRegex: "^986[0-9]{2}$", postalCodeExample: "98600", aliases: null },
  { code: "WS", nameRu: "Самоа", nameEn: "Samoa", phoneCode: "+685", phoneNumberMin: 5, phoneNumberMax: 7, postalCodeRegex: "^WS[0-9]{4}$", postalCodeExample: "WS1382", aliases: null },
  { code: "XK", nameRu: "Косово", nameEn: "Kosovo", phoneCode: "+383", phoneNumberMin: 8, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10000", aliases: null },
  { code: "YE", nameRu: "Йемен", nameEn: "Yemen", phoneCode: "+967", phoneNumberMin: 7, phoneNumberMax: 9, postalCodeRegex: null, postalCodeExample: null, aliases: null },
  { code: "YT", nameRu: "Майотта", nameEn: "Mayotte", phoneCode: "+262", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^976[0-9]{2}$", postalCodeExample: "97600", aliases: null },
  { code: "ZA", nameRu: "ЮАР", nameEn: "South Africa", phoneCode: "+27", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{4}$", postalCodeExample: "0001", aliases: "Южная Африка,South Africa" },
  { code: "ZM", nameRu: "Замбия", nameEn: "Zambia", phoneCode: "+260", phoneNumberMin: 9, phoneNumberMax: 9, postalCodeRegex: "^[0-9]{5}$", postalCodeExample: "10101", aliases: null },
  { code: "ZW", nameRu: "Зимбабве", nameEn: "Zimbabwe", phoneCode: "+263", phoneNumberMin: 8, phoneNumberMax: 10, postalCodeRegex: null, postalCodeExample: null, aliases: null },
];

// ЕС-27 (без Великобритании; Швейцария/Норвегия/Исландия — EEA, не ЕС).
const EU_CODES = new Set<string>([
  "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI", "FR",
  "DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU", "MT", "NL",
  "PL", "PT", "RO", "SK", "SI", "ES", "SE",
]);

async function main() {
  let created = 0;
  let updated = 0;

  for (const base of COUNTRIES) {
    const seed = { ...base, isEu: EU_CODES.has(base.code) };
    const existing = await prisma.country.findUnique({ where: { code: seed.code } });
    await prisma.country.upsert({
      where: { code: seed.code },
      update: seed,
      create: seed,
    });
    if (existing) {
      updated++;
    } else {
      created++;
    }
  }

  console.log(`Создано: ${created}`);
  console.log(`Обновлено: ${updated}`);
  console.log(`Всего записей в справочнике: ${COUNTRIES.length}`);

  await prisma.$disconnect();
}

main();
